#!/bin/sh
#
# Respawn <-> ET: Legacy config bridge for Wolfenstein: Enemy Territory.
#
# etlded is idTech3 and reads its settings from etl_server.cfg, not from env vars,
# so a secret written into CONTAINER_COMMAND would land in the ECS task definition in
# plaintext (and in `ps`). Respawn injects secrets as container ENVIRONMENT variables,
# so this shim writes rconpassword into a small overlay cfg that the server execs
# last, keeping the password in the task and out of the definition.
#
# It does NOT touch the stock /legacy/server/etmain/etl_server.cfg (4.7 KB of game
# rules, map cycle, etc.). etlded execs that first, then our overlay, so our values
# win without vendoring or editing the upstream config. fs_homepath is searched ahead
# of fs_basepath, so the overlay goes there.
#
# Runs as the image's `legacy` user (uid 1000), which owns both paths. Rewritten every
# start, so config stays declarative.
set -eu

HOMEPATH="/legacy/homepath"
OVERLAY_DIR="${HOMEPATH}/etmain"
OVERLAY="${OVERLAY_DIR}/respawn.cfg"

SERVERNAME="${SERVERNAME:-Respawn Enemy Territory}"
RCON_PASSWORD="${RCON_PASSWORD:-}"

mkdir -p "${OVERLAY_DIR}"
{
  echo "// Generated by Respawn on container start - do not edit by hand."
  echo "set sv_hostname \"${SERVERNAME}\""
  if [ -n "${RCON_PASSWORD}" ]; then
    echo "set rconpassword \"${RCON_PASSWORD}\""
  fi
} > "${OVERLAY}"

if [ -n "${RCON_PASSWORD}" ]; then
  rcon_state="set"
else
  rcon_state="unset (rcon disabled)"
fi
echo "Respawn: wrote ${OVERLAY} (hostname=${SERVERNAME}, rcon ${rcon_state})"

# Mirror the upstream entrypoint's launch, adding our overlay as the last +exec so it
# overrides the stock config. FS_GAME support is preserved for parity with the image.
FS_GAME_PARAM=""
if [ -n "${FS_GAME:-}" ]; then
  FS_GAME_PARAM="+set fs_game ${FS_GAME}"
fi

cd /legacy/server
# shellcheck disable=SC2086
exec ./etlded +set fs_homepath "${HOMEPATH}" ${FS_GAME_PARAM} \
  +exec etl_server.cfg +exec respawn.cfg "$@"
