#!/bin/sh
#
# Respawn <-> HLDS config bridge for the KZ (Kreedz climbing) CS 1.6 build.
#
# Same secret-handling reason as the other GoldSrc shims: jives/hlds forwards
# CONTAINER_COMMAND to hlds_run with no eval, so a secret named on the command line
# would arrive as that literal string. Secrets come in as env vars and are written to
# cfg files here, keeping them out of the task definition and out of `ps`.
#
# What makes this a KZ server rather than a deathmatch one is the cvars below. KZ is
# about climbing a course against the clock, so nearly everything CS does to structure
# a round is turned OFF: no round end, no freezetime, no buying, no team balance.
set -eu

GAME="${GAME:-cstrike}"
DIR="/opt/steam/hlds/${GAME}"
CFG="${DIR}/server.cfg"
AMXX_USERS="${DIR}/addons/amxmodx/configs/users.ini"

SERVERNAME="${SERVERNAME:-Respawn KZ}"
RCON_PASSWORD="${RCON_PASSWORD:-}"
AMXX_ADMIN_NAME="${AMXX_ADMIN_NAME:-admin}"
AMXX_ADMIN_PASSWORD="${AMXX_ADMIN_PASSWORD:-}"
FASTDL_URL="${FASTDL_URL:-}"

# Which generated cycle to run: all | starter | climb | bhop | hard | tier-<name>.
# Cycles are ordered easiest-first; `starter` is Beginner+Easy for a group new to KZ.
MAPCYCLE="${MAPCYCLE:-all}"

# --- KZ movement -------------------------------------------------------------
# Air acceleration is THE KZ cvar: it governs how much you can steer mid-air, which is
# what every jump technique depends on. 100 is the long-standing KZ standard and the
# value the maps and their records assume; stock CS is 10, on which most KZ maps are
# simply impossible.
AIRACCELERATE="${AIRACCELERATE:-100}"
# Stock CS gravity/speed. Changing these invalidates comparison with any published time.
GRAVITY="${GRAVITY:-800}"
MAXSPEED="${MAXSPEED:-320}"
# Minutes per map. Non-zero for the same reason as TFC: with 0, AMXX reads timeleft as
# 00:00 and map voting never opens. Long, because a hard climb is a long session.
TIMELIMIT="${TIMELIMIT:-45}"

{
  # ASCII only: GoldSrc's cfg parser predates UTF-8.
  echo "// Generated by Respawn on container start - do not edit by hand."
  echo "hostname \"${SERVERNAME}\""
  if [ -n "${RCON_PASSWORD}" ]; then echo "rcon_password \"${RCON_PASSWORD}\""; fi
  echo "mapcyclefile \"mapcycles/${MAPCYCLE}.txt\""
  echo "mp_timelimit ${TIMELIMIT}"
  echo "sv_allowdownload 1"
  echo "sv_allowupload 1"
  if [ -n "${FASTDL_URL}" ]; then echo "sv_downloadurl \"${FASTDL_URL}\""; fi
  echo "// --- KZ movement ---"
  echo "sv_airaccelerate ${AIRACCELERATE}"
  echo "sv_gravity ${GRAVITY}"
  echo "sv_maxspeed ${MAXSPEED}"
  echo "// --- stop CS structuring the session into rounds ---"
  echo "mp_round_infinite 1"
  echo "mp_freezetime 0"
  echo "mp_buytime 0"
  echo "mp_startmoney 0"
  echo "mp_autoteambalance 0"
  echo "mp_limitteams 0"
  echo "mp_friendlyfire 0"
  echo "mp_flashlight 1"
  # Climbing is not deathmatch: no forced respawn. A KZ timer plugin owns teleporting
  # the player back to the start, and a respawn under it would fight the run.
  echo "mp_forcerespawn 0"
} > "${CFG}"

if [ -n "${AMXX_ADMIN_PASSWORD}" ] && [ -f "${AMXX_USERS}" ]; then
  {
    echo "; Generated by Respawn on container start - do not edit by hand."
    echo "\"${AMXX_ADMIN_NAME}\" \"${AMXX_ADMIN_PASSWORD}\" \"abcdefghijklmnopqrstu\" \"ce\""
  } > "${AMXX_USERS}"
  amxx_state="admin '${AMXX_ADMIN_NAME}' configured"
else
  amxx_state="no admin (AMXX_ADMIN_PASSWORD unset)"
fi

# Fail loudly rather than boot with a cycle the vote cannot read.
CYCLE_FILE="${DIR}/mapcycles/${MAPCYCLE}.txt"
if [ ! -f "${CYCLE_FILE}" ]; then
  echo "Respawn: FATAL - no such mapcycle '${MAPCYCLE}'. Available:" >&2
  ls "${DIR}/mapcycles/" 2>/dev/null | sed 's/\.txt$//' | sed 's/^/  /' >&2
  exit 78
fi

if [ -n "${RCON_PASSWORD}" ]; then rcon_state="set"; else rcon_state="unset (rcon disabled)"; fi
if [ -n "${FASTDL_URL}" ]; then fastdl_state="${FASTDL_URL}"; else fastdl_state="disabled"; fi
echo "Respawn: wrote ${CFG} (hostname=${SERVERNAME}, rcon ${rcon_state})"
echo "Respawn: kz airaccelerate=${AIRACCELERATE} gravity=${GRAVITY}; amxx ${amxx_state}"
echo "Respawn: mapcycle ${MAPCYCLE} ($(grep -vc '^//' "${CYCLE_FILE}") maps); fastdl ${fastdl_state}"

cd /opt/steam/hlds
exec /bin/sh ./entrypoint.sh "$@"
