#!/bin/sh
#
# Respawn <-> HLDS config bridge for the MODDED (deathmatch) CS 1.6 build.
#
# Same reason as the vanilla shim: jives/hlds forwards CONTAINER_COMMAND to hlds_run
# with no eval, so a secret written as $RCON_PASSWORD on the command line would reach
# hlds as that literal string. Secrets arrive as container env vars and are written
# into cfg files here, keeping them out of the task definition and out of `ps`.
#
# This variant additionally writes the DEATHMATCH cvars. They are ReGameDLL's, not
# Valve's — `mp_forcerespawn`, `mp_randomspawn`, `mp_respawn_immunitytime` and
# `mp_round_infinite` do not exist on stock cs.so (verified by control test
# 2026-08-27), so this file is only meaningful on the ReGameDLL image.
set -eu

GAME="${GAME:-cstrike}"
DIR="/opt/steam/hlds/${GAME}"
CFG="${DIR}/server.cfg"
AMXX_USERS="${DIR}/addons/amxmodx/configs/users.ini"

SERVERNAME="${SERVERNAME:-Respawn CS 1.6 DM}"
RCON_PASSWORD="${RCON_PASSWORD:-}"
AMXX_ADMIN_NAME="${AMXX_ADMIN_NAME:-admin}"
AMXX_ADMIN_PASSWORD="${AMXX_ADMIN_PASSWORD:-}"

# --- deathmatch knobs (ReGameDLL) --------------------------------------------
# Seconds before a killed player respawns. 0 disables respawn entirely, which turns
# this back into round-based CS — so it is the one value not to set to 0 by accident.
DM_RESPAWN_DELAY="${DM_RESPAWN_DELAY:-2}"
# Random spawn points instead of team spawns. Needs the map's .nav file; without one
# ReGameDLL falls back to normal spawns rather than failing.
DM_RANDOM_SPAWN="${DM_RANDOM_SPAWN:-1}"
# Seconds of spawn protection. Stops spawn-camping, which FFA on a round map invites.
DM_SPAWN_IMMUNITY="${DM_SPAWN_IMMUNITY:-2}"
# Block round-end checks so the match does not keep ending — this is what actually
# makes it continuous deathmatch rather than very short rounds.
DM_ROUND_INFINITE="${DM_ROUND_INFINITE:-1}"
# 0 off, 1 infinite clip, 2 infinite backpack ammo.
DM_INFINITE_AMMO="${DM_INFINITE_AMMO:-2}"
# Buy time in minutes; -1 = always allowed, 0 = buying disabled.
DM_BUYTIME="${DM_BUYTIME:--1}"
# Minutes per map. Non-zero for the same reason as TFC: with 0, AMXX reads timeleft
# as 00:00 and map voting never opens.
TIMELIMIT="${TIMELIMIT:-30}"

# Overwrites the image's stock server.cfg. Safe: cstrike has no persistent volume and
# no SteamCMD install step, so nothing else writes this file.
{
  # ASCII only: GoldSrc's cfg parser predates UTF-8.
  echo "// Generated by Respawn on container start - do not edit by hand."
  echo "hostname \"${SERVERNAME}\""
  if [ -n "${RCON_PASSWORD}" ]; then
    echo "rcon_password \"${RCON_PASSWORD}\""
  fi
  echo "mapcyclefile \"mapcycle.txt\""
  echo "mp_timelimit ${TIMELIMIT}"
  echo "// --- deathmatch (ReGameDLL cvars; absent on stock cs.so) ---"
  echo "mp_forcerespawn ${DM_RESPAWN_DELAY}"
  echo "mp_randomspawn ${DM_RANDOM_SPAWN}"
  echo "mp_respawn_immunitytime ${DM_SPAWN_IMMUNITY}"
  echo "mp_round_infinite ${DM_ROUND_INFINITE}"
  echo "mp_infinite_ammo ${DM_INFINITE_AMMO}"
  echo "mp_buytime ${DM_BUYTIME}"
  echo "mp_auto_reload_weapons 1"
  echo "mp_refill_bpammo_weapons 2"
} > "${CFG}"

# AMXX admin: "<name>" "<password>" "<flags>" "<access>". ce = check name, need password.
if [ -n "${AMXX_ADMIN_PASSWORD}" ] && [ -f "${AMXX_USERS}" ]; then
  {
    echo "; Generated by Respawn on container start - do not edit by hand."
    echo "\"${AMXX_ADMIN_NAME}\" \"${AMXX_ADMIN_PASSWORD}\" \"abcdefghijklmnopqrstu\" \"ce\""
  } > "${AMXX_USERS}"
  amxx_state="admin '${AMXX_ADMIN_NAME}' configured"
else
  amxx_state="no admin (AMXX_ADMIN_PASSWORD unset)"
fi

if [ -n "${RCON_PASSWORD}" ]; then rcon_state="set"; else rcon_state="unset (rcon disabled)"; fi
echo "Respawn: wrote ${CFG} (hostname=${SERVERNAME}, rcon ${rcon_state})"
echo "Respawn: dm respawn=${DM_RESPAWN_DELAY}s immunity=${DM_SPAWN_IMMUNITY}s randomspawn=${DM_RANDOM_SPAWN}; amxx ${amxx_state}"

# Hand off to the upstream hlds entrypoint, preserving CONTAINER_COMMAND args.
cd /opt/steam/hlds
exec /bin/sh ./entrypoint.sh "$@"
