#!/bin/sh
#
# Respawn <-> HLDS config bridge for the MODDED Team Fortress Classic build.
#
# Same reason as the vanilla shim: jives/hlds forwards CONTAINER_COMMAND to
# hlds_run with no eval, so a secret written as $RCON_PASSWORD on the command line
# would reach hlds as that literal string. Secrets arrive as container env vars and
# are written into cfg files here instead, keeping them out of the task definition
# and out of `ps`.
#
# This variant writes two more things the vanilla one does not:
#
#   1. sv_downloadurl. HLDS throttles its OWN file transfer to 8 kB/s, so a client
#      joining without this would pull ~49 MB of custom maps and wads at dial-up
#      speed and almost certainly time out. FastDL is what makes custom maps
#      practical, not an optimisation.
#
#   2. The AMX Mod X admin entry. AMXX reads admins from configs/users.ini, which
#      wants a plaintext password, so it has to be generated at boot from the
#      injected secret rather than baked into the image.
set -eu

GAME="${GAME:-tfc}"
DIR="/opt/steam/hlds/${GAME}"
CFG="${DIR}/server.cfg"
AMXX_USERS="${DIR}/addons/amxmodx/configs/users.ini"

SERVERNAME="${SERVERNAME:-Respawn TFC}"
RCON_PASSWORD="${RCON_PASSWORD:-}"
# Base HTTP(S) URL serving a mirror of the tfc/ tree (maps/, *.wad, sound/, ...).
# Unset simply disables FastDL; the server still runs, just slowly for new clients.
FASTDL_URL="${FASTDL_URL:-}"
# AMXX in-game admin. Separate from rcon: this is the `amx_` command surface.
AMXX_ADMIN_NAME="${AMXX_ADMIN_NAME:-admin}"
AMXX_ADMIN_PASSWORD="${AMXX_ADMIN_PASSWORD:-}"
# Minutes per map. MUST be non-zero: with mp_timelimit 0 the AMXX nextmap plugin reads
# timeleft as 00:00, treats every map as already expired, and cycles to amx_nextmap
# immediately -- so a changelevel to any custom map bounces back to the boot map within
# seconds. Measured on this build 2026-08-27. It also disables map VOTING, because
# mapchooser opens its vote near map end and a map that never runs never gets there.
TIMELIMIT="${TIMELIMIT:-30}"

# Overwrites the image's stock server.cfg. Safe: tfc has no persistent volume and
# no SteamCMD install step, so nothing else writes this file. Rewritten every start,
# so config stays declarative.
{
  # ASCII only: GoldSrc's cfg parser predates UTF-8.
  echo "// Generated by Respawn on container start - do not edit by hand."
  echo "hostname \"${SERVERNAME}\""
  if [ -n "${RCON_PASSWORD}" ]; then
    echo "rcon_password \"${RCON_PASSWORD}\""
  fi
  echo "mapcyclefile \"mapcycle.txt\""
  echo "mp_timelimit ${TIMELIMIT}"
  # Clients must be allowed to download, and to fetch from the FastDL host.
  echo "sv_allowdownload 1"
  echo "sv_allowupload 1"
  if [ -n "${FASTDL_URL}" ]; then
    echo "sv_downloadurl \"${FASTDL_URL}\""
  fi
} > "${CFG}"

# AMXX admin. Format: "<name|ip|steamid>" "<password>" "<flags>" "<access flags>".
# ce = the name is checked and a password is required. abcdefghijklmnopqrstu is the
# full admin flag set; "ce" alone would authenticate but grant nothing.
if [ -n "${AMXX_ADMIN_PASSWORD}" ] && [ -f "${AMXX_USERS}" ]; then
  {
    echo "; Generated by Respawn on container start - do not edit by hand."
    echo "\"${AMXX_ADMIN_NAME}\" \"${AMXX_ADMIN_PASSWORD}\" \"abcdefghijklmnopqrstu\" \"ce\""
  } > "${AMXX_USERS}"
  amxx_state="admin '${AMXX_ADMIN_NAME}' configured"
else
  amxx_state="no admin (AMXX_ADMIN_PASSWORD unset)"
fi

if [ -n "${RCON_PASSWORD}" ]; then rcon_state="set"; else rcon_state="unset (rcon disabled)"; fi
if [ -n "${FASTDL_URL}" ]; then fastdl_state="${FASTDL_URL}"; else fastdl_state="disabled"; fi
echo "Respawn: wrote ${CFG} (hostname=${SERVERNAME}, rcon ${rcon_state})"
echo "Respawn: fastdl ${fastdl_state}; amxx ${amxx_state}; timelimit ${TIMELIMIT}m"

# Hand off to the upstream hlds entrypoint, preserving CONTAINER_COMMAND args.
cd /opt/steam/hlds
exec /bin/sh ./entrypoint.sh "$@"
