#!/usr/bin/env bash
# Regenerate mapcycles/ from maps.txt. maps.txt is the single source of truth; these
# files are DERIVED and tracked so the image can COPY them without the generator, and
# so drift between the two shows up as a diff in review rather than as a map that
# silently never appears in a vote.
#
# KZ differs from the TFC set in one way worth keeping: the cycles are ordered by
# DIFFICULTY, not alphabetically. A climb server that opens on a Hard map loses the
# room; opening on Beginner and ramping is the whole point of having tiers.
set -euo pipefail
here="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
manifest="$here/maps.txt"
out="$here/mapcycles"
mkdir -p "$out"

# Difficulty order as kreedz.com ranks them, easiest first.
TIERS=(Beginner Easy Easy-Medium Medium Medium-Hard Hard)

by_tier() { awk -v d="$1" '!/^#/ && NF==4 && $3==d {print $1}' "$manifest"; }
by_type() { awk -v t="$1" '!/^#/ && NF==4 && $2==t {print $1}' "$manifest"; }
# Ordered easiest -> hardest, preserving manifest order (download rank) within a tier.
ramp() { for d in "${TIERS[@]}"; do by_tier "$d"; done; }

emit() { # emit <file> <description> <maps...>
  local f="$out/$1"; shift; local desc="$1"; shift
  { echo "// GENERATED by scripts/generate-mapcycles.sh from maps.txt - do not edit."
    echo "// $desc"
    printf '%s\n' "$@"
  } > "$f"
  echo "  $(basename "$f"): $# maps"
}

# shellcheck disable=SC2046,SC2086
emit all.txt      "Every map, ordered easiest to hardest."        $(ramp)
emit starter.txt  "Beginner + Easy only - for a group new to KZ." $(by_tier Beginner) $(by_tier Easy)
emit climb.txt    "Climb maps only (the classic KZ style)."       $(by_type Climb)
emit bhop.txt     "Bhop maps only (speed//rhythm rather than precision)." $(by_type Bhop)
emit hard.txt     "Medium-Hard and above - for people who can already climb." \
                  $(by_tier Medium-Hard) $(by_tier Hard)
for d in "${TIERS[@]}"; do
  maps=$(by_tier "$d") || true
  [ -n "$maps" ] || continue
  # shellcheck disable=SC2086
  emit "tier-$(echo "$d" | tr 'A-Z' 'a-z').txt" "kreedz.com difficulty tier: $d" $maps
done

echo "regenerated $(ls "$out" | wc -l) cycles from $(grep -vc '^#' "$manifest") manifest entries"
