#!/bin/sh
#
# Respawn <-> HLDS config bridge for Counter-Strike 1.6.
#
# jives/hlds takes its game settings as hlds_run command-line args, and its
# entrypoint forwards them with no eval (`./hlds_run "-game $GAME $@"`), so a
# secret written as $RCON_PASSWORD in CONTAINER_COMMAND would reach hlds as that
# literal string. Respawn injects secrets as container ENVIRONMENT variables, so
# this shim writes them into cstrike/server.cfg — which GoldSrc execs at map
# start — keeping rcon out of the ECS task definition and out of `ps`.
#
# Runs as the image's `steam` user (uid 999), which owns the game dir, so no
# chown is needed. Rewritten on every start, so config stays declarative.
set -eu

GAME="${GAME:-cstrike}"
CFG="/opt/steam/hlds/${GAME}/server.cfg"

SERVERNAME="${SERVERNAME:-Respawn CS 1.6}"
RCON_PASSWORD="${RCON_PASSWORD:-}"
# Join password (sv_password). Injected as an ECS secret like rcon, so it never
# lands in the task definition; the shim writes it into server.cfg. Unset = open.
SERVER_PASSWORD="${SERVER_PASSWORD:-}"

# Overwrites the image's stock server.cfg. Safe here: cs16 has no persistent
# volume and no SteamCMD install step, so nothing else ever writes this file.
{
  # ASCII only: GoldSrc's cfg parser predates UTF-8 and this file is read by hlds.
  echo "// Generated by Respawn on container start - do not edit by hand."
  echo "hostname \"${SERVERNAME}\""
  if [ -n "${RCON_PASSWORD}" ]; then
    echo "rcon_password \"${RCON_PASSWORD}\""
  fi
  if [ -n "${SERVER_PASSWORD}" ]; then
    echo "sv_password \"${SERVER_PASSWORD}\""
  fi
  # Networking defaults. GoldSrc ships sv_maxupdaterate at 30, which caps every
  # client to 30 snapshots/sec regardless of their own rates and shows up as
  # "had to click twice to fire" (dropped +attack). 100+ with lag compensation
  # is the norm. Baked here so it survives the scale-to-zero cold start that a
  # live rcon change would not. Override per-server with GAME_ENV_* if needed.
  echo "sv_unlag 1"
  echo "sv_maxupdaterate ${SV_MAXUPDATERATE:-101}"
  echo "sv_minupdaterate ${SV_MINUPDATERATE:-20}"
  echo "sv_maxrate ${SV_MAXRATE:-100000}"
  echo "sv_minrate ${SV_MINRATE:-5000}"
} > "${CFG}"

if [ -n "${RCON_PASSWORD}" ]; then
  rcon_state="set"
else
  rcon_state="unset (rcon disabled)"
fi
echo "Respawn: wrote ${CFG} (hostname=${SERVERNAME}, rcon ${rcon_state})"

# Hand off to the upstream hlds entrypoint, preserving CONTAINER_COMMAND args.
cd /opt/steam/hlds
exec /bin/sh ./entrypoint.sh "$@"
