#!/usr/bin/env bash
#
# Respawn <-> Zandronum config bridge for Doom 2.
#
# The upstream image passes CONTAINER_COMMAND straight to `zandronum-server -host`,
# so setting sv_rconpassword there would put it in the task definition and in `ps`.
# Instead this shim writes it into a config the server +execs, keeping the rcon
# password off the command line (same idea as apps/cs16). Runs as root, like the
# upstream entrypoint, then hands off to it.
set -eu

RCON_PASSWORD="${RCON_PASSWORD:-}"

# The server +execs this; a custom name so nothing else overwrites it. It holds
# the secret cvar, kept out of the process args.
RCON_CFG="/tmp/respawn-rcon.cfg"
{
  echo "// Generated by Respawn on container start - do not edit."
  if [ -n "${RCON_PASSWORD}" ]; then
    echo "set sv_rconpassword \"${RCON_PASSWORD}\""
  fi
} > "${RCON_CFG}"
chmod 644 "${RCON_CFG}"
if [ -n "${RCON_PASSWORD}" ]; then
  echo "Respawn: wrote ${RCON_CFG} (sv_rconpassword set)"
else
  echo "Respawn: no RCON_PASSWORD set; rcon stays disabled"
fi

# Pick the IWAD: a retail doom2.wad uploaded to the EFS volume wins; otherwise the
# freedoom2.wad baked into the image, so the server starts with no manual step.
if [ -f /data/doom2.wad ]; then
  IWAD=/data/doom2.wad
else
  IWAD=/freedoom2.wad
fi
echo "Respawn: using IWAD ${IWAD}"

# Hand off to the upstream entrypoint with our iwad + rcon config prepended, then
# whatever CONTAINER_COMMAND passed (map, maxplayers, …).
exec /entrypoint.sh -iwad "${IWAD}" +exec "${RCON_CFG}" "$@"
