#!/bin/bash
#
# Respawn <-> LinuxGSM config bridge for Counter-Strike: Source.
#
# Like the gmod image, gameservermanagers/gameserver:css is config-FILE driven
# (no env vars for game settings). Respawn supplies config + secrets as container
# ENVIRONMENT variables, so this shim writes LinuxGSM's cssserver.cfg (and a
# server.cfg for the secret cvars) from those env vars, then hands off to the
# upstream entrypoint. Config is rewritten on every start (declarative).
set -euo pipefail

SERVERFILES="${LGSM_SERVERFILES:-/data/serverfiles}"
CFG_DIR="${LGSM_CONFIG:-/data/config-lgsm}/cssserver"
mkdir -p "${CFG_DIR}"

# Defaults mirror LinuxGSM's cssserver _default.cfg; Respawn env vars override.
DEFAULTMAP="${MAP:-de_dust2}"
MAXPLAYERS="${MAXPLAYERS:-16}"
SERVERNAME="${SERVERNAME:-Respawn CSS}"
PORT="${PORT:-27015}"
CLIENTPORT="${CLIENTPORT:-27005}"
SOURCETVPORT="${SOURCETVPORT:-27020}"
GSLT="${GSLT:-}"
RCON_PASSWORD="${RCON_PASSWORD:-}"

# srcds execs this at startup (+servercfgfile). Custom name so SteamCMD's install
# never overwrites it; it holds the secret cvars (rcon) off the command line.
SERVERCFG="respawn-server.cfg"

# LinuxGSM config: non-secret settings + GSLT (native gslt var -> +sv_setsteamaccount,
# the reliable way to publicly list). startparameters tracks the upstream _default.cfg.
cat > "${CFG_DIR}/cssserver.cfg" <<EOF
# Generated by Respawn from environment variables on container start.
# Do not edit by hand — overwritten on the next deploy/restart.
ip="0.0.0.0"
port="${PORT}"
clientport="${CLIENTPORT}"
sourcetvport="${SOURCETVPORT}"
defaultmap="${DEFAULTMAP}"
maxplayers="${MAXPLAYERS}"
gslt="${GSLT}"
servercfg="${SERVERCFG}"
startparameters="-game cstrike -strictportbind -ip \${ip} -port \${port} +clientport \${clientport} +tv_port \${sourcetvport} +sv_setsteamaccount \${gslt} +map \${defaultmap} +servercfgfile \${servercfg} -maxplayers \${maxplayers}"
EOF
echo "Respawn: wrote ${CFG_DIR}/cssserver.cfg (map=${DEFAULTMAP}, maxplayers=${MAXPLAYERS}, listed=$([ -n "${GSLT}" ] && echo yes || echo no))"

# server.cfg holds hostname + rcon_password (kept off the command line). Its dir
# (serverfiles/cstrike/cfg) only exists after SteamCMD installs the server, so
# write it from a background watcher once the dir appears — after the upstream
# "is serverfiles empty?" install check, so a first install is never blocked, and
# the custom filename means the install never clobbers it.
write_server_cfg() {
  local cfg_dir="${SERVERFILES}/cstrike/cfg"
  local target="${cfg_dir}/${SERVERCFG}"
  local waited=0
  while [ ! -d "${cfg_dir}" ]; do
    sleep 3
    waited=$((waited + 3))
    if [ "${waited}" -ge 1800 ]; then
      echo "Respawn: timed out waiting for ${cfg_dir}; ${SERVERCFG} not written"
      return 0
    fi
  done
  {
    echo "// Generated by Respawn on container start — do not edit by hand."
    echo "hostname \"${SERVERNAME}\""
    if [ -n "${RCON_PASSWORD}" ]; then
      echo "rcon_password \"${RCON_PASSWORD}\""
    fi
  } > "${target}"
  chown "${UID:-1000}:${GID:-1000}" "${target}" 2>/dev/null || true
  echo "Respawn: wrote ${target} (hostname + rcon)"
}
write_server_cfg &

# Hand off to the upstream LinuxGSM entrypoint (which drops to the linuxgsm user).
exec /bin/bash /app/entrypoint.sh
