#!/bin/bash
#
# Respawn <-> LinuxGSM config bridge.
#
# The upstream gameservermanagers/gameserver:gmod image is config-FILE driven:
# it has no environment variables for game settings (servername, gamemode, map,
# maxplayers, GSLT, rcon). Respawn, however, supplies all config + secrets as
# container ENVIRONMENT variables. This shim writes LinuxGSM's gmodserver.cfg
# (and a server.cfg for the secret cvars) from those env vars, then hands off to
# the upstream entrypoint.
#
# Runs as root (like the upstream entrypoint) and rewrites config on every start,
# so config is fully declarative from the Respawn .env / injected secrets.
set -euo pipefail

SERVERFILES="${LGSM_SERVERFILES:-/data/serverfiles}"
CFG_DIR="${LGSM_CONFIG:-/data/config-lgsm}/gmodserver"
mkdir -p "${CFG_DIR}"

# Defaults mirror LinuxGSM's gmodserver _default.cfg; Respawn env vars override.
GAMEMODE="${GAMEMODE:-sandbox}"
MAP="${MAP:-gm_construct}"
MAXPLAYERS="${MAXPLAYERS:-16}"
TICKRATE="${TICKRATE:-66}"
SERVERNAME="${SERVERNAME:-Respawn GMod}"
PORT="${PORT:-27015}"
CLIENTPORT="${CLIENTPORT:-27005}"
SOURCETVPORT="${SOURCETVPORT:-27020}"
GSLT="${GSLT:-}"
WORKSHOP_COLLECTION="${WORKSHOP_COLLECTION:-}"
RCON_PASSWORD="${RCON_PASSWORD:-}"

# srcds execs this file at startup (+servercfgfile). A custom name (not the stock
# server.cfg) so SteamCMD's install/validate never overwrites it. It holds the
# secret cvars (rcon_password) so they stay off the process command line / `ps`.
SERVERCFG="respawn-server.cfg"

# LinuxGSM config: non-secret game settings + GSLT. GSLT uses LinuxGSM's native
# `gslt` var (-> +sv_setsteamaccount on the command line), the reliable way to get
# the server publicly listed. startparameters tracks the upstream _default.cfg.
cat > "${CFG_DIR}/gmodserver.cfg" <<EOF
# Generated by Respawn from environment variables on container start.
# Do not edit by hand — overwritten on the next deploy/restart.
ip="0.0.0.0"
port="${PORT}"
clientport="${CLIENTPORT}"
sourcetvport="${SOURCETVPORT}"
tickrate="${TICKRATE}"
defaultmap="${MAP}"
gamemode="${GAMEMODE}"
maxplayers="${MAXPLAYERS}"
gslt="${GSLT}"
wscollectionid="${WORKSHOP_COLLECTION}"
servercfg="${SERVERCFG}"
startparameters="-game garrysmod -strictportbind -ip \${ip} -port \${port} -tickrate \${tickrate} +host_workshop_collection \${wscollectionid} +clientport \${clientport} +tv_port \${sourcetvport} +gamemode \${gamemode} +map \${defaultmap} +sv_setsteamaccount \${gslt} +servercfgfile \${servercfg} -maxplayers \${maxplayers} -disableluarefresh"
EOF
echo "Respawn: wrote ${CFG_DIR}/gmodserver.cfg (gamemode=${GAMEMODE}, map=${MAP}, maxplayers=${MAXPLAYERS}, listed=$([ -n "${GSLT}" ] && echo yes || echo no))"

# server.cfg holds hostname + rcon_password (kept off the command line). Its
# directory only exists after SteamCMD installs the server, so write it from a
# background watcher once the dir appears. This runs after the upstream
# "is serverfiles empty?" install check, so it never blocks a first install, and
# the custom filename means the install never clobbers it.
write_server_cfg() {
  local cfg_dir="${SERVERFILES}/garrysmod/cfg"
  local target="${cfg_dir}/${SERVERCFG}"
  local waited=0
  while [ ! -d "${cfg_dir}" ]; do
    sleep 3
    waited=$((waited + 3))
    if [ "${waited}" -ge 1800 ]; then
      echo "Respawn: timed out waiting for ${cfg_dir}; ${SERVERCFG} not written"
      return 0
    fi
  done
  {
    echo "// Generated by Respawn on container start — do not edit by hand."
    echo "hostname \"${SERVERNAME}\""
    if [ -n "${RCON_PASSWORD}" ]; then
      echo "rcon_password \"${RCON_PASSWORD}\""
    fi
  } > "${target}"
  # Match the runtime user (LinuxGSM runs as UID/GID, default 1000) so it's readable.
  chown "${UID:-1000}:${GID:-1000}" "${target}" 2>/dev/null || true
  echo "Respawn: wrote ${target} (hostname + rcon)"
}
write_server_cfg &

# Hand off to the upstream LinuxGSM entrypoint (which drops to the linuxgsm user).
exec /bin/bash /app/entrypoint.sh
