#!/usr/bin/env bash
# Regenerate mapcycles/ from maps.txt. maps.txt is the single source of truth for
# which maps exist and what kind each is; these files are DERIVED and tracked so the
# image can COPY them without needing the generator at build time.
#
# Run after editing maps.txt. Cycles are checked in, so a drift between the two shows
# up as a diff in review rather than as a map that silently never appears in a vote.
#
# Why generate rather than hand-write: a hand-written cycle drifts from the manifest
# the first time somebody adds a map and updates only one of them, and the failure is
# silent — mapchooser simply never offers the new map.
set -euo pipefail
here="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
manifest="$here/maps.txt"
out="$here/mapcycles"
mkdir -p "$out"

# Stock maps that ship with the base image. Kept out of the skill cycles on purpose:
# a skill server that drops back to 2fort between tracks is not a skill server.
STOCK=(2fort)

read_cat()  { awk -v c="$1" '!/^#/ && NF==4 && $2==c {print $1}' "$manifest" | sort; }
# The strongest provenance tiers — see maps.txt for what each source value means.
read_best() { awk '!/^#/ && NF==4 && ($3=="favorite" || $3=="rated-5" || $3=="rated-4") {print $1}' "$manifest" | sort; }

conc=$(read_cat conc); rocket=$(read_cat rocket); mixed=$(read_cat mixed)
[ -n "$conc$rocket$mixed" ] || { echo "no maps parsed from $manifest" >&2; exit 1; }

emit() { # emit <file> <description> <maps...>
  local f="$out/$1"; shift; local desc="$1"; shift
  { echo "// GENERATED by scripts/generate-mapcycles.sh from maps.txt - do not edit."
    echo "// $desc"
    printf '%s\n' "$@"
  } > "$f"
  echo "  $(basename "$f"): $# maps"
}

# shellcheck disable=SC2086
emit all.txt    "Everything: stock + every skill map."        ${STOCK[*]} $conc $rocket $mixed
emit skill.txt  "Skill maps only - no stock maps."            $conc $rocket $mixed
emit conc.txt   "Concussion-jump tracks only (scout/medic)."  $conc
emit rocket.txt "Rocket/grenade-jump tracks only (soldier)."  $rocket
emit stock.txt  "Stock TFC only - the vanilla rotation."      ${STOCK[*]}
# The short rotation: only maps with the strongest provenance. Deliberately small —
# a 20-map cycle is a rotation, this is a "play the good ones" list.
# shellcheck disable=SC2086
emit favorites.txt "Best-evidenced only (favorite / rated-5 / rated-4)." $(read_best)

echo "regenerated $(ls "$out" | wc -l) cycles from $(grep -vc '^#' "$manifest") manifest entries"
